apiVersion: v1
kind: Service
metadata:
  name: security-monitoring-service
spec:
  selector:
    app: security-monitoring
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
