# Flutter project dependencies and configurations
name: fitness_tracker_app
description: A fitness tracker application to monitor progress and set goals.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.16.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^4.9.0
  location: ^5.0.0
  google_maps_flutter: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

# Assets can be added here if required in the project
# assets:
#   - assets/