
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thatsallcloud-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: thatsallcloud-backend:latest
          ports:
            - containerPort: 5000
